import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; //폰트
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App - KDT01",
  description: "Generated by create next app",
};

export default function RootLayout({  //리액트와 달리 파일명과 이름(대문자로 시작)이 달라도됨 ///❗layout, page.tsx >>파일명,위치 절대 바꾸면 안됨
  children, //⭐리액트 노드 >>page.jsx
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //여기서 html 생성
    <html lang="ko"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="w-full h-screen flex flex-col">
          <header className="w-full min-h-20 bg-black mb-5 ">
            <div className="w-15 h-20 mx-10/12 flex flex-col justify-center items-center">
              < Nav />
            </div>
          </header>
          <main className="flex-grow w-full mx-10/12 flex flex-col justify-start items-center">
            {children}

          </main>
            <Footer/>
        </div>
      </body>
    </html>
  );
}
